version: "3"

services:

  insights-sdk-extensions-csharp-test:
    build: .
    container_name: insights-sdk-extensions-csharp-test
    image: finbourne/insights-sdk-extensions-csharp-test
    environment:
      - FBN_TOKEN_URL
      - FBN_USERNAME
      - FBN_PASSWORD
      - FBN_CLIENT_ID
      - FBN_CLIENT_SECRET
      - FBN_APP_NAME
      - FBN_INSIGHTS_API_URL=${FBN_BASE_API_URL}/insights
      - FBN_ACCESS_TOKEN
    volumes:
      - .:/usr/src